version: '3.6'
services:

  vninit:
    image: udpnnetwork/vninit:v1.7.0
    container_name: vninit
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - server.port=8080
      - spring.cloud.nacos.discovery.server-addr=nacos:8848
      - spring.cloud.nacos.discovery.username=nacos
      - spring.cloud.nacos.discovery.password=nacos
      - spring.cloud.nacos.discovery.namespace=vn
      - NACOS_ADDR=nacos:8848
      - NACOS_USERNAM=nacos
      - NACOS_PSW=nacos
      - NACOS_NAMESPACE=vn
    command: ["/bin/bash", "-c", "java -Djava.security.egd=file:/dev/./urandom -jar /app.jar"]
    volumes:
      - ${VN_DATA_VOLUMES}/log:/data:rw
      - ./vnserver/init/init_besu.yml:/data/init/init_besu.yml:rw
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${VN_INIT_PORT}:8080
    networks:
      - udpn-vn

  vngateway:
    image: udpnnetwork/chaingateway:v1.7.0
    container_name: vngateway
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - server.port=8080
      - spring.cloud.nacos.discovery.server-addr=nacos:8848
      - spring.cloud.nacos.discovery.username=nacos
      - spring.cloud.nacos.discovery.password=nacos
      - spring.cloud.nacos.discovery.namespace=vn
      - NACOS_ADDR=nacos:8848
      - NACOS_USERNAM=nacos
      - NACOS_PSW=nacos
      - NACOS_NAMESPACE=vn
    command: ["/bin/bash", "-c", "java -Djava.security.egd=file:/dev/./urandom -jar /app.jar"]
    volumes:
      - ${VN_DATA_VOLUMES}/log:/data:rw
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${VN_GATEWAY_PORT}:8080
    networks:
      - udpn-vn

  vnbase:
    image: udpnnetwork/vnbase:v1.7.0
    container_name: vnbase
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - server.port=8080
      - spring.cloud.nacos.discovery.server-addr=nacos:8848
      - spring.cloud.nacos.discovery.username=nacos
      - spring.cloud.nacos.discovery.password=nacos
      - spring.cloud.nacos.discovery.namespace=vn
      - NACOS_ADDR=nacos:8848
      - NACOS_USERNAM=nacos
      - NACOS_PSW=nacos
      - NACOS_NAMESPACE=vn
    command: ["/bin/bash", "-c", "java -Djava.security.egd=file:/dev/./urandom -jar /app.jar"]
    volumes:
      - ${VN_DATA_VOLUMES}/log:/data:rw
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${VN_BASE_PORT}:8080
    depends_on:
      - nacos
    networks:
      - udpn-vn

  vncontrol:
    image: udpnnetwork/vncontrol:v1.7.0
    container_name: vncontrol
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - server.port=8080
      - spring.cloud.nacos.discovery.server-addr=nacos:8848
      - spring.cloud.nacos.discovery.username=nacos
      - spring.cloud.nacos.discovery.password=nacos
      - spring.cloud.nacos.discovery.namespace=vn
      - NACOS_ADDR=nacos:8848
      - NACOS_USERNAM=nacos
      - NACOS_PSW=nacos
      - NACOS_NAMESPACE=vn
    command: ["/bin/bash", "-c", "java -Djava.security.egd=file:/dev/./urandom -jar /app.jar"]
    volumes:
      - ${VN_DATA_VOLUMES}/log:/data:rw
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${VN_CONTROL_PORT}:8080
    depends_on:
      - nacos
    networks:
      - udpn-vn

  vndid:
    image: udpnnetwork/vndid:v1.7.0
    container_name: vndid
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - server.port=8080
      - spring.cloud.nacos.discovery.server-addr=nacos:8848
      - spring.cloud.nacos.discovery.username=nacos
      - spring.cloud.nacos.discovery.password=nacos
      - spring.cloud.nacos.discovery.namespace=vn
      - NACOS_ADDR=nacos:8848
      - NACOS_USERNAM=nacos
      - NACOS_PSW=nacos
      - NACOS_NAMESPACE=vn
    command: ["/bin/bash", "-c", "java -Djava.security.egd=file:/dev/./urandom -jar /app.jar"]
    volumes:
      - ${VN_DATA_VOLUMES}/log:/data:rw
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${VN_DID_PORT}:8080
    depends_on:
      - nacos
    networks:
      - udpn-vn
  
  vnevent:
    image: udpnnetwork/vnevent:v1.7.0
    container_name: vnevent
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - server.port=8080
      - spring.cloud.nacos.discovery.server-addr=nacos:8848
      - spring.cloud.nacos.discovery.username=nacos
      - spring.cloud.nacos.discovery.password=nacos
      - spring.cloud.nacos.discovery.namespace=vn
      - NACOS_ADDR=nacos:8848
      - NACOS_USERNAM=nacos
      - NACOS_PSW=nacos
      - NACOS_NAMESPACE=vn
    command: ["/bin/bash", "-c", "java -Djava.security.egd=file:/dev/./urandom -jar /app.jar"]
    volumes:
      - ${VN_DATA_VOLUMES}/log:/data:rw
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${VN_EVENT_PORT}:8080
    depends_on:
      - vninit
    networks:
      - udpn-vn

  vnmember:
    image: udpnnetwork/vnmember:v1.7.0
    container_name: vnmember
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - server.port=8080
      - spring.cloud.nacos.discovery.server-addr=nacos:8848
      - spring.cloud.nacos.discovery.username=nacos
      - spring.cloud.nacos.discovery.password=nacos
      - spring.cloud.nacos.discovery.namespace=vn
      - NACOS_ADDR=nacos:8848
      - NACOS_USERNAM=nacos
      - NACOS_PSW=nacos
      - NACOS_NAMESPACE=vn
    command: ["/bin/bash", "-c", "java -Djava.security.egd=file:/dev/./urandom -jar /app.jar"]
    volumes:
      - ${VN_DATA_VOLUMES}/log:/data:rw
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${VN_MEMBER_PORT}:8080
    depends_on:
      - vninit
    networks:
      - udpn-vn
  
  vnpermission:
    image: udpnnetwork/vnpermission:v1.7.0
    container_name: vnpermission
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - server.port=8080
      - spring.cloud.nacos.discovery.server-addr=nacos:8848
      - spring.cloud.nacos.discovery.username=nacos
      - spring.cloud.nacos.discovery.password=nacos
      - spring.cloud.nacos.discovery.namespace=vn
      - NACOS_ADDR=nacos:8848
      - NACOS_USERNAM=nacos
      - NACOS_PSW=nacos
      - NACOS_NAMESPACE=vn
    command: ["/bin/bash", "-c", "java -Djava.security.egd=file:/dev/./urandom -jar /app.jar"]
    volumes:
      - ${VN_DATA_VOLUMES}/log:/data:rw
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${VN_PERMISSION_PORT}:8080
    depends_on:
      - vninit
    networks:
      - udpn-vn
  
  vnlogin:
    image: udpnnetwork/vnlogin:v1.7.0
    container_name: vnlogin
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - server.port=8080
      - spring.cloud.nacos.discovery.server-addr=nacos:8848
      - spring.cloud.nacos.discovery.username=nacos
      - spring.cloud.nacos.discovery.password=nacos
      - spring.cloud.nacos.discovery.namespace=vn
      - NACOS_ADDR=nacos:8848
      - NACOS_USERNAM=nacos
      - NACOS_PSW=nacos
      - NACOS_NAMESPACE=vn
    command: ["/bin/bash", "-c", "java -Djava.security.egd=file:/dev/./urandom -jar /app.jar"]
    volumes:
      - ${VN_DATA_VOLUMES}/log:/data:rw
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${VN_LOGIN_PORT}:8080
    depends_on:
      - vninit
    networks:
      - udpn-vn
  
  vntransaction:
    image: udpnnetwork/vntransaction:v1.7.0
    container_name: vntransaction
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - server.port=8080
      - spring.cloud.nacos.discovery.server-addr=nacos:8848
      - spring.cloud.nacos.discovery.username=nacos
      - spring.cloud.nacos.discovery.password=nacos
      - spring.cloud.nacos.discovery.namespace=vn
      - NACOS_ADDR=nacos:8848
      - NACOS_USERNAM=nacos
      - NACOS_PSW=nacos
      - NACOS_NAMESPACE=vn
    command: ["/bin/bash", "-c", "java -Djava.security.egd=file:/dev/./urandom -jar /app.jar"]
    volumes:
      - ${VN_DATA_VOLUMES}/log:/data:rw
      - ./vnserver/solc:/solc:rw
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${VN_TRANSACTION_PORT}:8080
    depends_on:
      - vninit
    networks:
      - udpn-vn
  
  vnsolutioncenter:
    image: udpnnetwork/vnsolutioncenter:v1.7.0
    container_name: vnsolutioncenter
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - server.port=8080
      - spring.cloud.nacos.discovery.server-addr=nacos:8848
      - spring.cloud.nacos.discovery.username=nacos
      - spring.cloud.nacos.discovery.password=nacos
      - spring.cloud.nacos.discovery.namespace=vn
      - NACOS_ADDR=nacos:8848
      - NACOS_USERNAM=nacos
      - NACOS_PSW=nacos
      - NACOS_NAMESPACE=vn
    command: ["/bin/bash", "-c", "java -Djava.security.egd=file:/dev/./urandom -jar /app.jar"]
    volumes:
      - ${VN_DATA_VOLUMES}/log:/data:rw
      - ./vnserver/solc:/solc:rw
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${VN_SOLUTIONCENTER_PORT}:8080
    depends_on:
      - vngateway
    networks:
      - udpn-vn
  
  vn-web:
    image: udpnnetwork/vnweb:v1.7.0
    container_name: vn-web
    restart: always
    volumes:
      - ${VN_DATA_VOLUMES}/vnweb/logs:/var/log/nginx
      - ./vnweb:/etc/nginx/conf.d/
    ports:
      - 8080:80
    networks:
      - udpn-vn
  
  vnsolutioncenter-web:
    image: udpnnetwork/vnsolutioncenterweb:v1.7.0
    container_name: vnsolutioncenter-web
    restart: always
    volumes:
      - ${VN_DATA_VOLUMES}/vnsolutioncenter-web/logs:/var/log/nginx
      - ./vnsolutioncenter-web:/etc/nginx/conf.d/
    ports:
      - 80:80
    depends_on:
      - vngateway
    networks:
      - udpn-vn

