# 1- if is no websocket then set empty of websocketPort
besu:
  inits:
    - nodeName: besu-a
      schema: http
      host: 16.162.201.215
      port: 8547
      websocketPort: 2831
    - nodeName: besu-b
      schema: http
      host: 16.162.201.215
      port: 8546
      websocketPort: 2830
